package org.boardgame.group37.view;
import javafx.scene.paint.Color;

/**
 * ColorPalette class provides a modern color scheme for the game.
 * Colors are organized into functional categories:
 * - BOARD_*: Colors for board tiles and board elements
 * - PLAYER_*: Colors for player tokens and player-related elements
 * - UI_*, BUTTON_*, DICE_*: Colors for interface elements
 * 
 * Color palette is generated by artificial inteligence (Claude 3.7)
 */
public final class ColorPalette {
    
    // Board colors - Modern muted palette
    public static final Color BOARD_LIGHT_TILE = Color.rgb(237, 242, 244); // Off-white
    public static final Color BOARD_DARK_TILE = Color.rgb(141, 153, 174);  // Slate blue
    public static final Color BOARD_TELEPORT_TILE = Color.rgb(239, 131, 84); // Coral
    public static final Color BOARD_MONOPOLY_TILE = Color.rgb(34, 139, 34); // Forest green
    public static final Color BOARD_BORDER = Color.rgb(43, 45, 66);        // Dark navy
    public static final Color BOARD_TEXT = Color.rgb(27, 27, 30);          // Near black
    
    // Player colors - Vibrant but harmonious
    public static final Color PLAYER_RED = Color.rgb(230, 57, 70);         // Modern red
    public static final Color PLAYER_BLUE = Color.rgb(65, 123, 217);       // Bright blue
    public static final Color PLAYER_GREEN = Color.rgb(76, 185, 130);      // Mint green
    public static final Color PLAYER_YELLOW = Color.rgb(241, 196, 15);     // Golden yellow
    public static final Color PLAYER_PURPLE = Color.rgb(155, 89, 182);     // Soft purple
    public static final Color PLAYER_ORANGE = Color.rgb(243, 156, 18);     // Carrot orange
    public static final Color PLAYER_PINK = Color.rgb(255, 105, 180);      // Hot pink

    public static Color[] getPlayerColors() {
        return new Color[] {PLAYER_RED, PLAYER_BLUE, PLAYER_GREEN, PLAYER_YELLOW, PLAYER_PURPLE, PLAYER_ORANGE, PLAYER_PINK};
    }
    
    // UI elements - Clean and accessible
    public static final Color UI_BACKGROUND = Color.rgb(122, 146, 163);    // Snow white
    public static final Color BUTTON_DEFAULT = Color.rgb(52, 152, 219);    // Clear blue
    public static final Color BUTTON_HOVER = Color.rgb(93, 173, 226);      // Lighter blue
    public static final Color UI_TEXT = Color.rgb(44, 62, 80);             // Dark slate
    public static final Color UI_SUCCESS = Color.rgb(46, 204, 113);        // Emerald green
    public static final Color UI_ERROR = Color.rgb(231, 76, 60);           // Flat red
    public static final Color DICE_BODY = Color.rgb(255, 255, 255);        // Pure white
    public static final Color DICE_DOTS = Color.rgb(52, 73, 94);           // Dark blue-gray
}